수정 need.yaml

diff --git a/.github/workflows/needs.yaml b/.github/workflows/needs.yaml
--- a/.github/workflows/needs.yaml
+++ b/.github/workflows/needs.yaml
@@ -10,28 +10,28 @@ jobs:
   job1:
     runs-on: ubuntu-latest
     steps:
-    - name: echo
-      run: echo "job1 done"
+      - name: echo
+        run: echo "job1 done"
 
   job2:
     runs-on: ubuntu-latest
     needs: [job1] #job1 성공시 job2 실행
     steps:
-    - name: echo
-      run: echo "job2 done"
+      - name: echo
+        run: echo "job2 done"
 
   job3:
     runs-on: ubuntu-latest
     steps:
-    - name: echo
-      run: |
-      echo "job3 failed"
-      exit 1 
+      - name: echo
+        run: |
+          echo "job3 failed"
+          exit 1
     # exit 1 사용시 강제 실패함
 
   job4:
     runs-on: ubuntu-latest
     needs: [job3]
     steps:
-    - name: echo
-      run: echo "job3 done"
+      - name: echo
+        run: echo "job3 done"
